void getword (char *word, char *line, char stop); 
char *makeword (char *line, char stop); 
char *fmakeword (FILE *f, char stop, int *cl); 
char x2c (char *what); 
void escape_url (char *url); 
void unescape_url (char *url); 
void plustospace (char *str); 
int rind (char *s, char c); 
void tobasename (char *s); 
char *basename (const char *name); 
void cutlast (char *s); 
int getline1 (char *s, int n, FILE *f); 
void send_fd (FILE *f, FILE *fd); 
void spacetoplus (char *str); 
void spacetounderscore (char *str); 
void str_replace (char *needle, char *string, char *haystack); 
int ldist(char *s,char*t);
int ldisti(char *s,char*t);
int min3(int a,int b,int c);
void getenvar(char *var, char *str, unsigned int len);
int varckfill(char *src, char *dest, char *str,int len);
